apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
      - name: nestjs-app
        image: prathm0025/nestjs-app:pr-1  # This will be replaced dynamically
        ports:
        - containerPort: 5001
        env:
        - name: MONGODB_URI
          value: ""
        - name: PORT
          value: "5001"
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-app-service
spec:
  type: NodePort
  selector:
    app: nestjs-app
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
