name: Build and Push Docker Image on PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract PR Number
        id: extract_pr_number
        run: echo "PR_NUMBER=$(echo ${{ github.event.pull_request.number }})" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-app:pr-${{ env.PR_NUMBER }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-app:pr-${{ env.PR_NUMBER }}

      - name: Confirm
        run: |
          echo "Docker image pushed: ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-app:pr-${{ env.PR_NUMBER }}"
