name: Build, Push, and Deploy to EKS on PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  build-push-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract PR Number
        id: extract_pr_number
        run: echo "PR_NUMBER=$(echo ${{ github.event.pull_request.number }})" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-app:pr-${{ env.PR_NUMBER }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-app:pr-${{ env.PR_NUMBER }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Update Deployment Image
        run: |
          sed -i "s|image: prathm0025/nestjs-app:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-app:pr-${{ env.PR_NUMBER }}|g" k8s/deployment.yaml

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/deployment.yaml

      - name: Confirm Deployment
        run: |
          kubectl rollout status deployment/nestjs-app
          echo "Deployment completed with image: ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-app:pr-${{ env.PR_NUMBER }}"
